#!/bin/python3

import random
import math
import sys

star_radius = 0.5
galaxy_density = .5
radius_of_galaxy = 100
volume_of_galaxy = (4.0/3.0) * math.pi * (radius_of_galaxy**3)
stars_in_galaxy = int(galaxy_density * volume_of_galaxy)


number_of_galaxies = 10
total_arrows = 10000



def cartestian(star):
    x = star[0]*math.cos(star[1])*math.sin(star[2])
    y = star[0]*math.sin(star[1])*math.sin(star[2])
    z = star[0]*math.cos(star[2])
    return x,y,z
#END CARTESIAN



def generate_galaxy():
    galaxy = []
    for star in range(stars_in_galaxy):
        radius = math.pow(random.uniform(0,1), 1/3) * radius_of_galaxy
        phi = random.uniform(0,2*math.pi)
        theta = math.acos( random.uniform(-1,1) )
        star = (radius,phi,theta)
        galaxy.append(star)
    galaxy.sort( key = lambda star: star[0] )
    return galaxy
#END GENERATE_FOREST



def arrow_hit_star(star, arrow_phi_angle, arrow_theta_angle):
    if star_radius > star[0]: #i.e. we start inside a star
        return True

    theta_angular_coverage = math.asin(star_radius / star[0])
    theta_angular_difference = abs(arrow_theta_angle - star[2])
    if theta_angular_difference < theta_angular_coverage:
        arc_length_coverage = abs(star_radius * math.cos(theta_angular_difference))
        radius_from_axis = star[0] * math.sin(arrow_theta_angle)
        if arc_length_coverage > radius_from_axis:
            return True

        phi_angular_coverage = math.asin(arc_length_coverage / radius_from_axis)
        phi_angular_difference = abs(arrow_phi_angle - star[1])
        if phi_angular_difference < phi_angular_coverage:
            return True
        elif phi_angular_difference > 2*math.pi - phi_angular_coverage:
            return True
        else:
            return False
    else:
        return False
#END ARROW_HIT_TREE



def travel_distance(galaxy, arrow_phi_angle, arrow_theta_angle):
    for star in galaxy:
        if arrow_hit_star(star, arrow_phi_angle, arrow_theta_angle):
            #print(str(star) + "  |  " + str(arrow_phi_angle) + ", " + str(arrow_theta_angle) )
            return star[0]
    return radius_of_galaxy
#END TRAVEL_DISTANCE



def shoot_arrows_into(galaxy):
    total_distance = 0.0
    for shot_num in range(total_arrows):
        arrow_phi_angle = random.uniform(0,2*math.pi)
        arrow_theta_angle = math.acos( random.uniform(-1,1) )
        total_distance += travel_distance(galaxy, arrow_phi_angle, arrow_theta_angle)

    average_distance = total_distance/total_arrows
    return average_distance
#END SHOOT_ARROWS_INTO



def main():
    if len(sys.argv) < 3:
        print("Usage: olber star_density star_radius")
        exit(0)
    unscaled_galaxy_density = float(sys.argv[1])
    unscaled_star_radius = float(sys.argv[2])

    average_total_distance = 0.0
    for galaxy_number in range(number_of_galaxies):
        galaxy = generate_galaxy()
        galaxy_average = shoot_arrows_into(galaxy)
        average_total_distance += galaxy_average
        print("Finished galaxy " + str(galaxy_number) + ", unscaled average = " + str(galaxy_average))
    final_average_distance = average_total_distance / number_of_galaxies

    scale_factor = (galaxy_density/unscaled_galaxy_density) * ( (star_radius/unscaled_star_radius)**2 )
    scaled_average = final_average_distance * scale_factor
    print("AVERAGE SCALED DISTANCE TRAVELLED = " + str(scaled_average))
#END MAIN



main()
